version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
    command: ["npm", "run", "server-start:test"]
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --port 27017 --bind_ip_all

volumes:
  mongo-data:
